server:
  port: 8012

shiro:
  loginUrl: /login.html

spring:
  datasource:
    username: root
    password: 159629zxc
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

#打印sql 语句
logging:
  level:
    com.phoenixhell.shiro: debug

